### ISSUE TITLE
Can't get .jsbeautifyrc to work

### ISSUE THREAD

**Issue by blairvanderhoof** [jdc0589/JsFormat#102]
I want to enable/disable format_on_save for certain projects at the `.jsbeautifyrc` file level.  I have done the following:

1) Go to the user preferences for js format and add:
````
{
  "jsbeautifyrc_files": true
}
````
2) Create `.jsbeautifyrc` and add to the file:
````
{
  "format_on_save": true
}
````
3) Restart Sublime just to be safe.  Format on save does not work.

**Comment by jdc0589** [comment]
closing this in favor of #124
