### ISSUE TITLE
JsFormat isn't formatting all my .js files with the same indent

### ISSUE THREAD

**Issue by seglo** [jdc0589/JsFormat#111]
Sublime Text 3 Build: 3059

Some of my files in my NPM project are formatted with my user indent settings ("tab_size": 2,), but other files in my project default to 4.  I can't figure out why.  I don't have any other config in my project.  I don't see any errors in the sublime console.

Can anyone suggest any other options to troubleshoot this?

**Comment by eTorAken** [comment]
Agree with @jdc0589, to avoid this I recommend using [EditorConfig-Sublime](https://github.com/sindresorhus/editorconfig-sublime) with these parameters:
```
indent_style = space
indent_size = 2
```

**Comment by jdc0589** [comment]
@eTorAken How does it behave with files that already have indentation that varies from what you have defined in your user settings.  I would imaging it behaves the same as sublime-core does?

**Comment by eTorAken** [comment]
@jdc0589 You might be right, I will check this next time it happens to me.

**Comment by dbnapp** [comment]
Not sure if everyone figured it out but I think I found the fix. It was a sublime setting I had to override, not a JsFormat issue.

I had to add
```
{
    "detect_indentation": false
}
```
to Preferences > Settings - User

**Comment by jdc0589** [comment]
@dbnapp prefect. Thanks.

**Comment by peterrecore** [comment]
I had to fix the "detect_indentation" and "indent_style" and "indent_size"  in both my user preferences (Preferences > Settings - User) AND the **JavaScript specific settings (Preferences > Settings - Syntax Specific)** .  The syntax specific settings were overriding everything else.
