### ISSUE TITLE
** Virus **

### ISSUE THREAD

**Issue by Ademir-Francisco-da-Silva** [jdc0589/JsFormat#128]
Unfortunately I have found one virus inside the JSFormat, so please fix it asap and just release a clean version, thanks ...

Malware@#32y6pefzv999b

**Comment by jdc0589** [comment]
uhhh, can you be more specific?

**Comment by Ademir-Francisco-da-Silva** [comment]
On 21/02/2015 14:17, Davis Clark wrote:
>
> uhhh, can you be more specific?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jdc0589/JsFormat/issues/128#issuecomment-75378598>.
>

Yes I really can, but there isn't more details to inform you, I mean 
..., after I install it my antivirus just send a message accusing this 
malware and every time I have tried to reinstall it, my only solution 
was uninstall it util you provide a clean version ... thank you for your 
understanding.

-- 
Ademir Francisco da Silva
Skype  ...: Ademir_Francisco_da_Silva
[ CMC ] God will do me justice

**Comment by jdc0589** [comment]
Your antivirus is....wrong. JsFormat contains no malicious code, and no networking related code.
If you would like to be sure that you are getting the clean source that is available for open review here on github, install the plugin manually to take any other variable out of the equation.

I don't know how much antivirus experience you have, but 99% of them are basically worthless.
