### ISSUE TITLE
ES7 async / await

### ISSUE THREAD

**Issue by Xiot** [jdc0589/JsFormat#129]
I am currently using babel to transpile my code so that I can use the fancy new es6/7 features.
One thing that I noticed was that formatting in Sublime Text 3 puts a newline after the async keyword which breaks the build.

```
async function(){
}
```

becomes

```
async
function(){
}
```

Is there anyway to control the line breaks specifically for the async keyword?

**Comment by Xiot** [comment]
I submitted a PR for this on  beautify-web/js-beautify#630 which in going to be included in the 1.6.0 milestone

**Comment by jdc0589** [comment]
@Xiot   looks like 1.6.2 just landed, will try and get js-beautify upgraded here soon.
