### ISSUE TITLE
Possible to selectively disable jsFormat?

### ISSUE THREAD

**Issue by gebrits** [jdc0589/JsFormat#131]
Is it possible to selectively disable formatting for a particular region of code? For instance using some sort of comment? 

use-case: i've got a multiline mustache template, that gets totally mangled on save because of jsFormat.

**Comment by jdc0589** [comment]
Not currently. What's you method for the multiline strings?

**Comment by gebrits** [comment]
Something like this:

var txt = "some text \
 something more";

**Comment by bitwiseman** [comment]
Multiline strings are supported... 
Can you give a better example that includes mustache?

**Comment by jdc0589** [comment]
@bitwiseman huh, ive missed that somehow. does it just attempt to leave relative indentation as is?

**Comment by bitwiseman** [comment]
It attempts to make no changes inside the string.  This is sort of required to avoid adding extra whitespace:
```js
{
    var a = "A Multiline string \
should only have one space between \
any word."
```

**Comment by jdc0589** [comment]
closing this. reopen if it's still an issue.
