### ISSUE TITLE
JSON array formatting

### ISSUE THREAD

**Issue by carlosmcp** [jdc0589/JsFormat#135]
When i use the JsFormat in sublime, i'm getting like this:

``` javascript
{
 'Z':  [
            { 
              nome: 'A',
              index: 0 
             },
             {
              nome: 'B',
               index: 1 
             }              
     ]
}
```

So, i would like to get like this:

``` javascript
{
 'Z': [
                { nome: 'A', index: 0 }, 
                { nome: 'B', index: 1 }
      ]
}
```

It's possible?

**Comment by bitwiseman** [comment]
Waiting on this: https://github.com/beautify-web/js-beautify/issues/315

**Comment by jdc0589** [comment]
looks like recently got merged in js-beautify. marking this as `jsbeautifier-upgrade`

**Comment by bitwiseman** [comment]
@jdc0589 -
Users will need to use the new brace-style: "collapse-preserve-inline" to make this work.
