### ISSUE TITLE
what's wrong? jsformat not works in st2?

### ISSUE THREAD

**Issue by chapgaga** [jdc0589/JsFormat#138]
ctrl+alt+f also not works, confusing
![](http://img.itc.cn/photo/jfBqRCX0GUV)

**Comment by jdc0589** [comment]
resolved. something went wrong with a merge from earlier.

**Comment by chapgaga** [comment]
will package manager automatically update package when their is newer one?

**Comment by chapgaga** [comment]
@jdc0589  in fact you are wrong, now st3 and st2 both not work with jsformat, you don't fix the bug, but introduce new bug:(

**Comment by jdc0589** [comment]
can you open up the sublime console and see what the error is?

there have been intermittent package control ir github issues (not sure
which)  with invalid zip file headers lately.
