### ISSUE TITLE
The newest version updated by 'Package Control' not work

### ISSUE THREAD

**Issue by WuChu** [jdc0589/JsFormat#141]
hi,
The commend panel reported some syntax error when I use sublime 2. I installed the newest version by 'Package Control'. And the JSON-style code maybe also some error here in 'JsFormat.sublime-settings'. The program can't resolve it.

**Comment by hyperknot** [comment]
Yes, wanted to confirm this. Removing the comma fixes the problem, but the default settings should not be tinkered by the user.
