### ISSUE TITLE
Installation via Package Control don't show 'jsformat'

### ISSUE THREAD

**Issue by srfrnk** [jdc0589/JsFormat#145]
Trying to use package control to install the plugin.
i have an ubuntu distro - ST3. probably latest package control.
tried adding repo as instructed by readme.
still the package list doesn't show jsformat.
please help.

**Comment by jdc0589** [comment]
@srfrnk JsFormat is included in the default Package Control channel, you shouldn't have to add it manually. Try removing that repo you set up.
