### ISSUE TITLE
Not working - Sublime Text 3 on Mac

### ISSUE THREAD

**Issue by nerijunior** [jdc0589/JsFormat#152]
I've installed and on cmd+shift+p doesn't show `Format: Javascript`

**Comment by jdc0589** [comment]
@nerijunior you have to be in a js/json file, or the buffer syntax has to be set to javascript for it to show up.

**Comment by nerijunior** [comment]
@jdc0589 Yep! I'm on js file.

**Comment by sashavtyurina** [comment]
You need to setup the type of the file to JavaScript (the tab in the bottom right corner). This worked for me.

**Comment by jimklo** [comment]
i'll second this issue, but it seems worse.  It's not installing via Package Control.

**Comment by nerijunior** [comment]
@jimklo Yeah!!! I've reinstalled the package, restarted ST3 and now it's working!

**Comment by jdc0589** [comment]
do you get any output in the sublime console?

**Comment by Lumend** [comment]
no installation python3?
