### ISSUE TITLE
How can I set  "space_before_conditional": false ?

### ISSUE THREAD

**Issue by khaledosman** [jdc0589/JsFormat#153]
I tried going to preferences -> package settings -> jsformat -> Settings - User and
added   "space_before_conditional": false , but it doesn't seem to work

**Comment by jdc0589** [comment]
@khaledosman did you try completely exiting and reloading sublime after the change? you shouldn't have to....

**Comment by bitwiseman** [comment]
@jdc0589 
Sorry - https://github.com/beautify-web/js-beautify/issues/807
