### ISSUE TITLE
Preserve ${ on ES6

### ISSUE THREAD

**Issue by GuilhermeReda** [jdc0589/JsFormat#157]
Hi, I have a file with the following code.

``` javascript
`SELECT
  nextval('${this.options.schema ? `${this.options.schema}.` : ''}"${this.tableName}_${this.autoIncrementField}_seq"'::regclass
) nextval;`
```

When I format the file, that line becomes

``` javascript
`SELECT
  nextval('${this.options.schema ? `
  $ {
    this.options.schema
  }.
  ` : ''}"${this.tableName}_${this.autoIncrementField}_seq"'::regclass
) nextval;`
```

it is putting a space between $ and {, and that breaks my code.

**Comment by jdc0589** [comment]
this does not appear to be happening anymore. re-open if necessary. I think you may have had some errant backticks in your example as well, but I'm not sure.
