### ISSUE TITLE
Indent multi-line  annotation each command in html？ 

### ISSUE THREAD

**Issue by pingfengafei** [jdc0589/JsFormat#163]
Here is  a section in my html file, format manually ：
![image](https://cloud.githubusercontent.com/assets/6243826/12288281/c121ffaa-ba0d-11e5-867f-2b174d3e12c7.png)

after command：
![image](https://cloud.githubusercontent.com/assets/6243826/12288302/f083695a-ba0d-11e5-8ccb-abfe666d70bb.png)

jsformat indent uncorrectly.

here is my user config:

``` code
{
    // exposed jsbeautifier options
    "indent_with_tabs": true,
    "preserve_newlines": true,
    "max_preserve_newlines": 4,
    "space_in_paren": false,
    "jslint_happy": false,
    "brace_style": "collapse",
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "eval_code": false,
    "unescape_strings": false,
    "break_chained_methods": false,
    "e4x": false,
    "wrap_line_length": 0,

    // jsformat options
    "format_on_save": false,
    "format_selection": true,
    "jsbeautifyrc_files": false,
    "ignore_sublime_settings": true,
    "format_on_save_extensions": ["js", "json"]
}

```

How to solve it ?

**Comment by jdc0589** [comment]
JsFormat isn't really intended to be used on html files. If you *really* want use it in html files, you can highlight the contents of your script tag (including leading whitespace on the first line), and it will just format the selection.
