### ISSUE TITLE
ES6 Space After Method

### ISSUE THREAD

**Issue by gpresland** [jdc0589/JsFormat#164]
Error keeps showing up on all ES6 methods.

```JavaScript
class MyClass {
  constructor() {
    //       ^---error here
  }
}
```

It is expecting a space as if it is an anonymous function.

**Comment by bitwiseman** [comment]
Please provide a link to the part of the spec that outlines this. Just so we can make sure to get any fix right.

**Comment by jdc0589** [comment]
@gpresland a js-beautifier upgrade is inbound soon. lets retest after that lands.

**Comment by mathieug** [comment]
#166

**Comment by rizkyramadhan** [comment]
I still have this issue.

![capture](https://cloud.githubusercontent.com/assets/126301/19630590/9a231e0e-99b7-11e6-8a05-a08cc5f82ab0.PNG)
