### ISSUE TITLE
ES7 Decorators

### ISSUE THREAD

**Issue by zj8487** [jdc0589/JsFormat#168]
I am currently using babel to transpile my code so that I can use the fancy new es6/7 features.
One thing that I noticed was that formatting in Sublime Text 3 puts a newline after the @ keyword which breaks the build.
js
```
@test
class Test {
}
```

becomes

async
```
@
test
class Test {
}
```
Is there anyway to control the line breaks specifically for the @ keyword?

**Comment by jdc0589** [comment]
@zj8487 open up an issue in the [js-beautify](https://github.com/wycats/javascript-decorators) tracker. That's where it will need to be fixed.
