### ISSUE TITLE
ImportError: No module named _fileio

### ISSUE THREAD

**Issue by thiagoh** [jdc0589/JsFormat#171]
Hello there, 

I'm getting the following error when trying to install the jsformatter

Ubuntu 15.10
Sublime 2 Build: 2221

```
Reloading plugin /home/thiagoh/.config/sublime-text-2/Packages/JsFormat/js_formatter.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./js_formatter.py", line 37, in <module>
    import jsbeautifier, jsbeautifier.unpackers
  File "/home/thiagoh/.config/sublime-text-2/Packages/JsFormat/libs/jsbeautifier/__init__.py", line 4, in <module>
    import io
  File ".\io.py", line 63, in <module>
ImportError: No module named _fileio
```

**Comment by jdc0589** [comment]
@thiagoh I'll take a look. Out of curiosity, whats keeping you from upgrading to ST3?

**Comment by thiagoh** [comment]
@jdc0589 unfortunately, using sublime2 is a rule in my office because sublime3 is still in beta.

**Comment by thiagoh** [comment]
@jdc0589 have you had any luck solving the issue?

**Comment by jdc0589** [comment]
we still have a little work to do to clean some of this up, but especially now that ST3 is "officially" out, I don't think ST2 support is going to be a huge priority any more. I'll do what I can though.
