### ISSUE TITLE
JsFormat Error. Invalid JSON

### ISSUE THREAD

**Issue by Hiroki1116** [jdc0589/JsFormat#178]
![screen shot 2017-05-25 at 1 12 54 pm](https://cloud.githubusercontent.com/assets/9676341/26434515/90af6174-414c-11e7-9e1f-5db882f1182d.png)

Whenever I save a file, there appears a message, saying that "JsFormat Error. Invalid JSON ... jsbeautifyrc".

This happens even when the file is empty.
As you can see in the background in the pic attached, this warning is displayed when there is nothing in a JS file.

Here is the content of jsFormat.sublime-settings.

{
  "break_chained_methods": false,
  "brace_style": "end-expand",
  "preserve_newlines": true,
  "max_preserve_newlines": 2,
  "e4x": true,
  "jsbeautifyrc_files": true,
  "format_on_save": true,
  "format_on_save_extensions": ["js", "json"]
}

Has anyone encountered this issue before?
Any advice will be appreciated.

**Comment by jdc0589** [comment]
Here's what's happening:

1. the `jsbeautifyrc_files` setting is set to `true`, so JsFormat looks for a `.jsbeautifyrc` settings file based on [this criteria](https://github.com/jdc0589/JsFormat#jsbeautifyrc-files).
2. It found a settings file at the path in the window you censored out, and that file has invalid JSON in it, which can not be parsed; hence the error message.

You just need to fix whatever invalid json is in the `.jsbeautifyrc` file and you should be good to go.
