### ISSUE TITLE
adding new keywords into JsFormat

### ISSUE THREAD

**Issue by arabnejad** [jdc0589/JsFormat#179]
Hi all
I am wondering if we can add new keywords for highlighting and formatting in JsFormat package for sublime text 3 ?

Regards,
Hamid

**Comment by bitwiseman** [comment]
@arabnejad - Cloud you be more specific?  Which keywords?

**Comment by arabnejad** [comment]
Hi @bitwiseman 
I am using an program witch get .js file as input with some additional keywords, for example
```
aspectdef name_aspect
       input [param_list] end
       output  [param_list]  end
       body_aspect
end
```
has similar functionality to -> function keywords
OR
```
select  var_name end
       apply
               body
       end
```
the only thing I am looking for is to how define these type of keywords in order to have correct highlighting and formatting in my .js file at sublime

Regards,
Hamid

**Comment by bitwiseman** [comment]
@arabnejad That looks very little like javascript. 😄  

Sorry, there's no configuration option for adding keywords. You can make your own fork that has new keywords.   If you create a version that takes keywords as configuration options, I'd be happy to consider merging it.  

Thanks!
