### ISSUE TITLE
Breaks async/await

### ISSUE THREAD

**Issue by etiennea** [jdc0589/JsFormat#181]
My problem is that
`
async (req, res) => {}
`
gets formatted to 
`
async(req, res) => {}
`

The space that get removed makes this invalid, this rule should not happen when there is an async.

**Comment by jdc0589** [comment]
@etiennea: what javascript platform are you on? node? 
on node `v8.1.4` I have no issues with or without the space. That said, I don't think JsBeautifier exposes a setting to control this right now.

**Comment by bitwiseman** [comment]
@etiennea also this is fixed in JsBeautifier 1.7.4, released today.

**Comment by etiennea** [comment]
Good news! Thanks!

**Comment by jdc0589** [comment]
just merged #184, this should be resolved
