### ISSUE TITLE
how to setting the import style？

### ISSUE THREAD

**Issue by Sailor20** [jdc0589/JsFormat#182]
![image](https://user-images.githubusercontent.com/24997729/30730364-0e638820-9f99-11e7-950e-b711d4ba5008.png)

when format the code, the import code was break to more lines, i did not want this, what should i do?

**Comment by jdc0589** [comment]
@Sailor20: you want to play around with the `brace_style` setting; the options are:
- expand
- collapse
- collapse-preserve-inline
- end-expand
- none

I generally end up using `collapse-preserve-inline`. Basically, it tries to detect if you were shooting for an all inline, or all expanded format and respects it.
