### ISSUE TITLE
Support comma first style of variable declaration

### ISSUE THREAD

**Issue by mrchief** [jdc0589/JsFormat#59]
Allow code to be formatted like this:

```
var a = 1
  , b = "somethign else"
  , isAwesome = true;
```

JSBeautifier supports it (or can be tweaked easily): http://stackoverflow.com/questions/10872184/comma-first-js-formatter
https://gist.github.com/nemtsov/2864266

**Comment by bitwiseman** [comment]
It took a while, but the initial implementation of this is available in v1.5.5 of js-beautify.
