### ISSUE TITLE
HTML support

### ISSUE THREAD

**Issue by mmohamad** [jdc0589/JsFormat#62]
Is it possible to incorporate html support.

**Comment by felixhao28** [comment]
It will be awesome if this supports html formatting. And it will still be cool if this only supports <script> tags. But to start with, it should not format the whole html file.

**Comment by jdc0589** [comment]
I'm not planning on adding HTML formatting support to this plugin. It would be nice, but this plugin is going to stay focused on plain old javascript/json.

The best thing to do for this functinality would be start a new plugin based on the logic JsFormat already has for interacting with sublime, but refactor things to support any language via formatting/beautifier plugins (much like sublime linter does for code analysis). I started this a **long** time ago in the [Format](https://github.com/jdc0589/Format) project (which is based on a SUPER old version of JsFormat). I don't think it's a project I want to tackle myself right now, but I'd be more than happy to help out from time to time if someone else wanted to spearhead it.
