### ISSUE TITLE
Anonymous Function vs Named Function Paren Spacing

### ISSUE THREAD

**Issue by tswood** [jdc0589/JsFormat#64]
Hello.

I've noticed that with JsFormat, my anonymous functions are getting formatted like my named functions, as such:

``` javascript
var fn = function NamedFn() {
    // Code
};

var fn2 = function() {
    // More Code
};
```

On jsbeautifier.org, and the way I've learned/read/seen, anonymous functions have a space between the function keyword and the starting parens.

``` javascript
var fn = function () {
  // Code
};
```

**Comment by justin808** [comment]
Worth noting:

1. WebStorm & RubyMine don't yet support having no space: https://youtrack.jetbrains.com/issue/WEB-7368
2. http://javascript.crockford.com/code.html specifies one space.

**Comment by reacher-lu** [comment]
@dertseha Well done!
